package view;

import controller.SessaoController;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Filme;
import model.Sala;
import servico.FilmeServico;
import servico.SalaServico;
import servico.SessaoServico;
import util.DateUtil;

/**
 *
 * @author silvinha01
 */
public class PainelFormularioSessao extends javax.swing.JPanel {

    private SessaoController controller;
    private SessaoServico servicoSessao;
    private SalaServico servicoSala;
    private FilmeServico servicoFilme;

    /**
     * Creates new form PainelFormularioSessao
     */
    public PainelFormularioSessao() {
        initComponents();
    }

    PainelFormularioSessao(SessaoController controller) {
        initComponents();
        this.controller = controller;
        servicoSessao = new SessaoServico();
        servicoSala = new SalaServico();
        servicoFilme = new FilmeServico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        textNomeSala1 = new javax.swing.JTextField();
        jLabelCodigoSala = new javax.swing.JLabel();
        labelPainelFormularioSessao = new javax.swing.JLabel();
        botaoSalvarSessao = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        textCodigoSala = new javax.swing.JTextField();
        jLabelQtdAssentos = new javax.swing.JLabel();
        textQtdAssentos = new javax.swing.JTextField();
        jLabelHorario = new javax.swing.JLabel();
        textHorario = new javax.swing.JTextField();

        jLabelCodigoSala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodigoSala.setText("Código Sala:");

        labelPainelFormularioSessao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPainelFormularioSessao.setText("Cadastro de Sessões");

        botaoSalvarSessao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSalvarSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastrar.png"))); // NOI18N
        botaoSalvarSessao.setText("Cadastrar Sessão");
        botaoSalvarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarSessaoActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabelQtdAssentos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQtdAssentos.setText("Código Filme:");

        jLabelHorario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelHorario.setText("Horário (hh:mm):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(175, 175, 175)
                                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPainelFormularioSessao)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabelHorario)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                                        .addComponent(textHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabelCodigoSala)
                                                                .addComponent(jLabelQtdAssentos))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(textCodigoSala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(textQtdAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(botaoSalvarSessao)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(47, 47, 47))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{textQtdAssentos, textCodigoSala, textHorario});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{botaoSalvarSessao, botaoVoltar});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(labelPainelFormularioSessao)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCodigoSala)
                                .addComponent(textCodigoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textQtdAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelQtdAssentos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelHorario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoSalvarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoVoltar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{botaoSalvarSessao, botaoVoltar});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{textQtdAssentos, textCodigoSala, textHorario});

    }// </editor-fold>                        

    public JButton getBotaoSalvar() {
        return botaoSalvarSessao;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

    public JLabel getLabelPainelFormularioSessao() {
        return labelPainelFormularioSessao;
    }

    public JTextField getTextCodigoSala() {
        return textCodigoSala;
    }

    /*public JTextField getTextQtdAssentos() {
     return textQtdAssentos;
     }*/
    public JTextField getTextCodigoFilme() {
        return textCodigoFilme;
    }

    public JTextField getTextHorario() {
        return textHorario;
    }

    public void zerarCampos() {
        this.textCodigoSala.setText("");
        //this.textQtdAssentos.setText("");
        this.textCodigoFilme.setText("");
        this.textHorario.setText("");
    }

    public void carregaDados(int codigosala, int qtdassentos, int codigofilme, Date horario) {
        String codsala = String.valueOf(codigosala);
        String assentos = String.valueOf(qtdassentos);
        String codfilme = String.valueOf(codigofilme);
        //String horario = String.valueOf(horario);

        this.textCodigoSala.setText(codsala);
        //this.textQtdAssentos.setText(assentos);
        this.textCodigoFilme.setText(codfilme);
        //this.textHorario.setText(horario);
    }

    public void habilitaEdicaoFormSessao(boolean valor) {
        this.textCodigoSala.setEditable(valor);
        //this.textQtdAssentos.setEditable(valor);
        this.textCodigoFilme.setEditable(valor);
        this.textHorario.setEditable(valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigoSala = new javax.swing.JLabel();
        labelPainelFormularioSessao = new javax.swing.JLabel();
        botaoSalvarSessao = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        textCodigoSala = new javax.swing.JTextField();
        jLabelCodigoFilme = new javax.swing.JLabel();
        textCodigoFilme = new javax.swing.JTextField();
        jLabelHorario = new javax.swing.JLabel();
        textHorario = new javax.swing.JTextField();

        jLabelCodigoSala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodigoSala.setText("Código Sala:");

        labelPainelFormularioSessao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPainelFormularioSessao.setText("Cadastro de Sessões");

        botaoSalvarSessao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSalvarSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastrar.png"))); // NOI18N
        botaoSalvarSessao.setText("Cadastrar Sessão");
        botaoSalvarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarSessaoActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabelCodigoFilme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodigoFilme.setText("Código Filme:");

        jLabelHorario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelHorario.setText("Horário (hh:mm):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHorario)
                            .addComponent(jLabelCodigoFilme)
                            .addComponent(jLabelCodigoSala))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCodigoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCodigoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoSalvarSessao)
                                .addGap(8, 8, 8)
                                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelPainelFormularioSessao))
                        .addGap(25, 25, 25))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoSalvarSessao, botaoVoltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelPainelFormularioSessao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigoSala)
                    .addComponent(textCodigoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigoFilme)
                    .addComponent(textCodigoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHorario)
                    .addComponent(textHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoSalvarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoSalvarSessao, botaoVoltar});

    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarSessaoActionPerformed
        int idsala = Integer.parseInt(textCodigoSala.getText());
        Sala sala = servicoSala.mostrarSalaPorId(idsala);
        if (!servicoSala.salaIdExiste(idsala)) {
            PrintUtil.printMessageError(null, "Sala não encontrada!");
        } else {

            int qtdAssentosDisponiveis = sala.getQtdAssentos();

            int idfilme = Integer.parseInt(textCodigoFilme.getText());
            Filme filme = servicoFilme.mostrarFilmePorId(idfilme);
            if (!servicoFilme.filmeIdExiste(idfilme)) {
                PrintUtil.printMessageError(null, "Filme não encontrado!");
            } else {

                Date horario = null;
                try {
                    horario = DateUtil.stringToHour(textHorario.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(PainelFormularioSessao.class.getName()).log(Level.SEVERE, null, ex);
                }
                servicoSessao.buscarSessaoPorSalaEHorario(idsala, horario);
                if (servicoSessao.sessaoPorSalaEHorarioExiste(idsala, horario)) {
                    PrintUtil.printMessageError(null, "Sala e horario estão ocupados!");
                } else {

                    controller.salvarSessao(
                            sala,
                            qtdAssentosDisponiveis,
                            filme,
                            horario
                    );
                }
            }
        }
    }//GEN-LAST:event_botaoSalvarSessaoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_botaoVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarSessao;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabelCodigoFilme;
    private javax.swing.JLabel jLabelCodigoSala;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel labelPainelFormularioSessao;
    private javax.swing.JTextField textCodigoFilme;
    private javax.swing.JTextField textCodigoSala;
    private javax.swing.JTextField textHorario;
    // End of variables declaration//GEN-END:variables
}
