package view;

import controller.VendaController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Sessao;
import servico.SessaoServico;
import servico.VendaServico;

/**
 *
 * @author silvinha01
 */
public class PainelFormularioVenda extends javax.swing.JPanel {

    private VendaController controller;
    private VendaServico servicoVenda;
    private SessaoServico servicoSessao;

    /**
     * Creates new form PainelFormularioVenda
     */
    public PainelFormularioVenda() {
        initComponents();
    }

    PainelFormularioVenda(VendaController controller) {
        initComponents();
        this.controller = controller;
        servicoVenda = new VendaServico();
        servicoSessao = new SessaoServico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        textNomeSala1 = new javax.swing.JTextField();
        jLabelCodigoSessao = new javax.swing.JLabel();
        labelPainelFormularioVenda = new javax.swing.JLabel();
        botaoSalvarVenda = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        textCodigoSessao = new javax.swing.JTextField();
        jLabelIngressos = new javax.swing.JLabel();
        textIngressos = new javax.swing.JTextField();
        jLabelHorario = new javax.swing.JLabel();
        textHorario = new javax.swing.JTextField();

        jLabelCodigoSessao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodigoSessao.setText("Código Sala:");

        labelPainelFormularioVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPainelFormularioVenda.setText("Cadastro de Sessões");

        botaoSalvarVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSalvarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastrar.png"))); // NOI18N
        botaoSalvarVenda.setText("Cadastrar Sessão");
        botaoSalvarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarSessaoActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabelIngressos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelIngressos.setText("Código Filme:");

        jLabelHorario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelHorario.setText("Horário (hh:mm):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(175, 175, 175)
                                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPainelFormularioVenda)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabelHorario)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                                        .addComponent(textHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabelCodigoSessao)
                                                                .addComponent(jLabelIngressos))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(textCodigoSessao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(textIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(botaoSalvarVenda)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(47, 47, 47))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{textIngressos, textCodigoSessao, textHorario});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{botaoSalvarVenda, botaoVoltar});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(labelPainelFormularioVenda)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCodigoSessao)
                                .addComponent(textCodigoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelIngressos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelHorario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoSalvarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoVoltar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{botaoSalvarVenda, botaoVoltar});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{textIngressos, textCodigoSessao, textHorario});

    }// </editor-fold>                        

    public JButton getBotaoSalvar() {
        return botaoSalvarVenda;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

    public JLabel getLabelPainelFormularioVenda() {
        return labelPainelFormularioVenda;
    }

    public JTextField getTextCodigoSessao() {
        return textCodigoSessao;
    }

    public JTextField getTextIngressos() {
        return textIngressos;
    }

    public void zerarCampos() {
        this.textCodigoSessao.setText("");
        this.textIngressos.setText("");
    }

    public void carregaDados(int codigosessao, int qtdingressos) {
        String codsessao = String.valueOf(codigosessao);
        String ingressos = String.valueOf(qtdingressos);

        this.textCodigoSessao.setText(codsessao);
        this.textIngressos.setText(ingressos);
    }

    public void habilitaEdicaoFormVenda(boolean valor) {
        this.textCodigoSessao.setEditable(valor);
        this.textIngressos.setEditable(valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigoSessao = new javax.swing.JLabel();
        labelPainelFormularioVenda = new javax.swing.JLabel();
        botaoSalvarVenda = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        textCodigoSessao = new javax.swing.JTextField();
        jLabelIngressos = new javax.swing.JLabel();
        textIngressos = new javax.swing.JTextField();

        jLabelCodigoSessao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodigoSessao.setText("Código Sessão:");

        labelPainelFormularioVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPainelFormularioVenda.setText("Cadastro de Vendas");

        botaoSalvarVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSalvarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastrar.png"))); // NOI18N
        botaoSalvarVenda.setText("Cadastrar Venda");
        botaoSalvarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarVendaActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabelIngressos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelIngressos.setText("Ingressos (qtd):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSalvarVenda)
                        .addGap(8, 8, 8)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelPainelFormularioVenda)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodigoSessao)
                            .addComponent(jLabelIngressos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textCodigoSessao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoSalvarVenda, botaoVoltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelPainelFormularioVenda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigoSessao)
                    .addComponent(textCodigoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIngressos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoSalvarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoSalvarVenda, botaoVoltar});

    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarVendaActionPerformed
        int idsessao = Integer.parseInt(textCodigoSessao.getText());
        Sessao sessao = servicoSessao.mostrarSessaoPorId(idsessao);
        if (servicoSessao.sessaoIdExiste(idsessao)) {

            if ((sessao.getQtdAssentosDisponiveis()) <= 0) {
                PrintUtil.printMessageError(null, "\nEsta sessão está com lotação esgotada!");
                PrintUtil.printMessageError(null, "\nIngressos disponíveis para venda: " + (sessao.getQtdAssentosDisponiveis()));
            } else {
                PrintUtil.printMessageError(null, "\nIngressos disponíveis para venda: " + (sessao.getQtdAssentosDisponiveis()));

                int qtdIngressos = Integer.parseInt(textIngressos.getText());

                if ((sessao.getQtdAssentosDisponiveis()) < qtdIngressos) {
                    PrintUtil.printMessageError(null, "A quantidade de ingressos disponíveis é inferior à solicitação!");
                    PrintUtil.printMessageError(null, "\nIngressos disponíveis para venda: " + (sessao.getQtdAssentosDisponiveis()));
                } else if (qtdIngressos <= 0) {
                    PrintUtil.printMessageError(null, "A quantidade de ingressos para compra deverá ser maior que zero!");
                } else {

                    controller.salvarVenda(
                            sessao,
                            qtdIngressos
                    );
                }
            }
        } else {
            PrintUtil.printMessageError(null, "Código da sessão não encontrado!");
        }
    }//GEN-LAST:event_botaoSalvarVendaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_botaoVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarVenda;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabelCodigoSessao;
    private javax.swing.JLabel jLabelIngressos;
    private javax.swing.JLabel labelPainelFormularioVenda;
    private javax.swing.JTextField textCodigoSessao;
    private javax.swing.JTextField textIngressos;
    // End of variables declaration//GEN-END:variables
}
