package view;

import controller.FilmeController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import servico.FilmeServico;

/**
 *
 * @author silvinha01
 */
public class PainelFormularioFilme extends javax.swing.JPanel {

    private FilmeController controller;
    private FilmeServico servicoFilme;

    /**
     * Creates new form PainelFormulario
     */
    public PainelFormularioFilme() {
        initComponents();
    }

    PainelFormularioFilme(FilmeController controller) {
        this.controller = controller;
        servicoFilme = new FilmeServico();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoSalvarFilme = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        textNomeFilme = new javax.swing.JTextField();
        textGenero = new javax.swing.JTextField();
        textSinopse = new javax.swing.JTextField();
        jLabelNomeFilme = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelSinopse = new javax.swing.JLabel();
        labelPainelFormularioFilme = new javax.swing.JLabel();

        botaoSalvarFilme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSalvarFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastrar.png"))); // NOI18N
        botaoSalvarFilme.setText("Cadastrar Filme");
        botaoSalvarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarFilmeActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabelNomeFilme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeFilme.setText("Nome:");

        jLabelGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGenero.setText("Gênero:");

        jLabelSinopse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSinopse.setText("Sinopse:");

        labelPainelFormularioFilme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPainelFormularioFilme.setText("Cadastro de Filmes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPainelFormularioFilme)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoSalvarFilme)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelGenero)
                                .addComponent(jLabelSinopse)
                                .addComponent(jLabelNomeFilme))
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textGenero, textNomeFilme, textSinopse});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoSalvarFilme, botaoVoltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelPainelFormularioFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeFilme))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGenero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSinopse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarFilme, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textGenero, textNomeFilme, textSinopse});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoSalvarFilme, botaoVoltar});

    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoSalvarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarFilmeActionPerformed
        String nome = (textNomeFilme.getText());
        if (servicoFilme.filmeNomeExiste(nome)) {
            PrintUtil.printMessageError(null, "Filme de nome " + "'" + nome + "'" + " já está cadastrado!");
        } else if (nome.equals("")) {
            PrintUtil.printMessageError(null, "O campo Nome do filme não poderá ficar em branco!");
        } else {

            String genero = (textGenero.getText());
            if (genero.equals("")) {
                PrintUtil.printMessageError(null, "O campo Gênero não poderá ficar em branco!");
            } else {

                String sinopse = (textSinopse.getText());
                if ((sinopse.equals(""))) {
                    PrintUtil.printMessageError(null, "O campo Sinopse não poderá ficar em branco!");
                } else {

                    controller.salvarFilme(
                            nome,
                            genero,
                            sinopse);
                }
            }
        }
    }//GEN-LAST:event_botaoSalvarFilmeActionPerformed

    public JButton getBotaoSalvar() {
        return botaoSalvarFilme;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

    public JLabel getLabelPainelFormularioFilme() {
        return labelPainelFormularioFilme;
    }

    public JTextField getTextNome() {
        return textNomeFilme;
    }

    public JTextField getTextGenero() {
        return textGenero;
    }

    public JTextField getTextSinopse() {
        return textSinopse;
    }

    public void zerarCampos() {
        this.textNomeFilme.setText("");
        this.textGenero.setText("");
        this.textSinopse.setText("");
    }

    public void carregaDados(String nome, String genero, String sinopse) {
        this.textNomeFilme.setText(nome);
        this.textGenero.setText(genero);
        this.textSinopse.setText(sinopse);
    }

    public void habilitaEdicaoFormFilme(boolean valor) {
        this.textNomeFilme.setEditable(valor);
        this.textGenero.setEditable(valor);
        this.textSinopse.setEditable(valor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarFilme;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNomeFilme;
    private javax.swing.JLabel jLabelSinopse;
    private javax.swing.JLabel labelPainelFormularioFilme;
    private javax.swing.JTextField textGenero;
    private javax.swing.JTextField textNomeFilme;
    private javax.swing.JTextField textSinopse;
    // End of variables declaration//GEN-END:variables

}
