package view;

import controller.SalaController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import servico.SalaServico;

/**
 *
 * @author silvinha01
 */
public class PainelFormularioSala extends javax.swing.JPanel {

    private SalaController controller;
    private SalaServico servicoSala;

    /**
     * Creates new form PainelFormularioSala
     */
    public PainelFormularioSala() {
        initComponents();
    }

    PainelFormularioSala(SalaController controller) {
        this.controller = controller;
        servicoSala = new SalaServico();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeSala = new javax.swing.JLabel();
        jLabelQtdAssentos = new javax.swing.JLabel();
        labelPainelFormularioSala = new javax.swing.JLabel();
        botaoSalvarSala = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        textNomeSala = new javax.swing.JTextField();
        textQtdAssentos = new javax.swing.JTextField();

        jLabelNomeSala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeSala.setText("Nome Sala:");

        jLabelQtdAssentos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQtdAssentos.setText("Assentos (qtd):");

        labelPainelFormularioSala.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPainelFormularioSala.setText("Cadastro de Salas");

        botaoSalvarSala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSalvarSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastrar.png"))); // NOI18N
        botaoSalvarSala.setText("Cadastrar Sala");
        botaoSalvarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarSalaActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPainelFormularioSala)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSalvarSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQtdAssentos)
                            .addComponent(jLabelNomeSala))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textQtdAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textNomeSala, textQtdAssentos});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoSalvarSala, botaoVoltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelPainelFormularioSala)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNomeSala)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelQtdAssentos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textQtdAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textNomeSala, textQtdAssentos});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoSalvarSala, botaoVoltar});

    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarSalaActionPerformed
        String nome = (textNomeSala.getText());
        if (servicoSala.salaNomeExiste(nome)) {
            PrintUtil.printMessageError(null, "Sala de nome " + "'" + nome + "'" + " já está cadastrada!");
        } else if ((nome.equals(""))) {
            PrintUtil.printMessageError(null, "O campo Nome da sala não poderá ficar em branco!");
        } else {
            
            int qtdassentos = Integer.parseInt(textQtdAssentos.getText());
            if ((qtdassentos <= 0)) {
                PrintUtil.printMessageError(null, "O campo Quantidade de Assentos deverá ser maior que zero!");
            } else {
                
             //controle para campo vazio de inteiros   
                controller.salvarSala(
                        nome,
                        qtdassentos
                );
            }
        }
    }//GEN-LAST:event_botaoSalvarSalaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    public JButton getBotaoSalvar() {
        return botaoSalvarSala;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

    public JLabel getLabelPainelFormularioSala() {
        return labelPainelFormularioSala;
    }

    public JTextField getTextNome() {
        return textNomeSala;
    }

    public JTextField getTextQtdAssentos() {
        return textQtdAssentos;
    }

    public void zerarCampos() {
        this.textNomeSala.setText("");
        this.textQtdAssentos.setText("");
    }

    public void carregaDados(String nome, int qtdassentos) {
        String quantassentos = String.valueOf(qtdassentos);
        this.textNomeSala.setText(nome);
        this.textQtdAssentos.setText(quantassentos);
    }

    public void habilitaEdicaoFormSala(boolean valor) {
        this.textNomeSala.setEditable(valor);
        this.textQtdAssentos.setEditable(valor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarSala;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabelNomeSala;
    private javax.swing.JLabel jLabelQtdAssentos;
    private javax.swing.JLabel labelPainelFormularioSala;
    private javax.swing.JTextField textNomeSala;
    private javax.swing.JTextField textQtdAssentos;
    // End of variables declaration//GEN-END:variables
}
